### ISSUE TITLE
Model Size

### ISSUE THREAD

**Issue by GanjinZero** [GanjinZero/ChineseEHRBert#1]
- A standard size for GPU (like bert-base)
- A mini size for mobile device

**Comment by GanjinZero** [comment]
Device:
Tesla V100 16GB * 2

**Comment by cronousbaby** [comment]
您好 请问一下这个模型预训练是时间是多少，预训练的规模？

**Comment by GanjinZero** [comment]
1个月+，100G+raw text

**Comment by cronousbaby** [comment]
thanks！2080ti 可以训练吗，100G指的纯病历数据还是医学类期刊或医学网站知识呢

**Comment by GanjinZero** [comment]
> thanks！2080ti 可以训练吗，100G指的纯病历数据还是医学类期刊或医学网站知识呢

可以，就是慢。纯病历

**Comment by knowleton** [comment]
大佬你好，请问一下，对同时有文本和CT图像的数据，您有推荐的获取方法吗，我最近想做两种融合的，但苦于找不到数据 @GanjinZero

**Comment by GanjinZero** [comment]
> 大佬你好，请问一下，对同时有文本和CT图像的数据，您有推荐的获取方法吗，我最近想做两种融合的，但苦于找不到数据 @GanjinZero

抱歉这种数据我也没有

**Comment by knowleton** [comment]
好吧，谢谢啦

**Comment by zhjohnchan** [comment]
Thanks for your great repo. Could you please tell me how to acquire the data for pretraining. Is it private data or publically available?

**Comment by GanjinZero** [comment]
> Thanks for your great repo. Could you please tell me how to acquire the data for pretraining. Is it private data or publically available?

private data from hospitals

**Comment by zhjohnchan** [comment]
@GanjinZero thanks~
