### ISSUE TITLE
Hello, would you like list the performance comparison of downstream tasks?

### ISSUE THREAD

**Issue by crazyofapple** [GanjinZero/ChineseEHRBert#3]
I wonder if you can share some results which would give me a great of help in comprehending your methods and making some comparisons with mine. I will be appreciated for your reply as soon as possible, thank you very much!

**Comment by GanjinZero** [comment]
Sorry, the results of ChineseEHRBert is unavailable due to the privacy policy. If you want to compare your result with the Google's original bert, you can use our test script. I will update the comparison between ChineseEHRBert and original bert once available.

**Comment by crazyofapple** [comment]
OK, thank you! Can the statistics of downstream tasks be listed? Because it seems that some data sets need to be divided.

**Comment by GanjinZero** [comment]
> OK, thank you! Can the statistics of downstream tasks be listed? Because it seems that some data sets need to be divided.

I will update them soon.
